import "server-only";
import { getSql } from "./db";
import { logActivity } from "./activity";

// GSTR-2B is generated by the government from suppliers' own GSTR-1 filings —
// we can only download it (from the GST portal) and reconcile it against our
// purchase records. schema.ts declares gstr2b_uploads/gstr2b_records, but self
// -migrate too (mirrors ensureActivityTable()) so this works before any db:push.
let ensured: Promise<void> | null = null;
function ensureTables(): Promise<void> {
  if (!ensured) {
    const sql = getSql();
    ensured = (async () => {
      await sql`CREATE TABLE IF NOT EXISTS gstr2b_uploads (
        id serial PRIMARY KEY,
        period text NOT NULL,
        file_name text DEFAULT '',
        uploaded_by text,
        created_at text DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
      )`;
      await sql`CREATE TABLE IF NOT EXISTS gstr2b_records (
        id serial PRIMARY KEY,
        upload_id integer NOT NULL,
        supplier_gstin text DEFAULT '',
        supplier_name text DEFAULT '',
        invoice_no text DEFAULT '',
        invoice_date text DEFAULT '',
        taxable_value double precision DEFAULT 0,
        igst double precision DEFAULT 0,
        cgst double precision DEFAULT 0,
        sgst double precision DEFAULT 0,
        itc_availability text DEFAULT '',
        raw_json jsonb
      )`;
      await sql`CREATE INDEX IF NOT EXISTS gstr2b_upload_idx ON gstr2b_records (upload_id)`;
    })().catch((e) => { ensured = null; throw e; });
  }
  return ensured;
}

// GSTN dates in the portal JSON are DD-MM-YYYY; normalize to YYYY-MM-DD so
// string comparisons against our own invoice_date/bill_date columns work.
function normDate(d: string): string {
  const m = /^(\d{2})-(\d{2})-(\d{4})$/.exec(String(d ?? "").trim());
  return m ? `${m[3]}-${m[2]}-${m[1]}` : String(d ?? "").trim();
}

export interface ParsedGstr2bRecord {
  supplierGstin: string; supplierName: string; invoiceNo: string; invoiceDate: string;
  taxableValue: number; igst: number; cgst: number; sgst: number; itcAvailability: string;
}

// Tolerant of the two real shapes GSTN's portal export uses ({data:{docdata:...}}
// or {docdata:...}) plus a flat {b2b:[...]} shape for hand-built test files.
export function parseGstr2bJson(raw: unknown): { records: ParsedGstr2bRecord[]; errors: string[] } {
  const errors: string[] = [];
  const root = raw as Record<string, unknown>;
  const docdata = (root?.data as Record<string, unknown>)?.docdata ?? root?.docdata ?? root;
  const b2b = (docdata as Record<string, unknown>)?.b2b;
  if (!Array.isArray(b2b)) { errors.push("Could not find a b2b[] section in this file — is it the GSTR-2B JSON downloaded from the GST portal?"); return { records: [], errors }; }

  const records: ParsedGstr2bRecord[] = [];
  for (const supplier of b2b as Record<string, unknown>[]) {
    const ctin = String(supplier.ctin ?? "").trim().toUpperCase();
    const trdnm = String(supplier.trdnm ?? "");
    const invs = Array.isArray(supplier.inv) ? (supplier.inv as Record<string, unknown>[]) : [];
    for (const inv of invs) {
      const items = Array.isArray(inv.itms) ? (inv.itms as Record<string, unknown>[]) : [];
      let taxable = 0, igst = 0, cgst = 0, sgst = 0;
      for (const it of items) {
        const det = (it.itm_det as Record<string, unknown>) ?? it;
        taxable += Number(det.txval ?? 0) || 0;
        igst += Number(det.igst ?? 0) || 0;
        cgst += Number(det.cgst ?? 0) || 0;
        sgst += Number(det.sgst ?? 0) || 0;
      }
      records.push({
        supplierGstin: ctin, supplierName: trdnm,
        invoiceNo: String(inv.inum ?? "").trim(), invoiceDate: normDate(String(inv.idt ?? "")),
        taxableValue: taxable, igst, cgst, sgst,
        itcAvailability: String(inv.itcavl ?? inv.itc_avl ?? ""),
      });
    }
  }
  if (records.length === 0) errors.push("Found a b2b[] section but no invoice records inside it.");
  return { records, errors };
}

export async function uploadGstr2b(input: { period: string; fileName: string; uploadedBy: string | null; uploadedByRole?: string | null; raw: unknown }): Promise<{ id: number; count: number } | { error: string }> {
  await ensureTables();
  const { records, errors } = parseGstr2bJson(input.raw);
  if (records.length === 0) return { error: errors[0] ?? "No records found in this file." };

  const sql = getSql();
  const [upload] = await sql`INSERT INTO gstr2b_uploads (period, file_name, uploaded_by) VALUES (${input.period}, ${input.fileName}, ${input.uploadedBy}) RETURNING id`;
  const uploadId = (upload as { id: number }).id;
  for (const r of records) {
    await sql`INSERT INTO gstr2b_records (upload_id, supplier_gstin, supplier_name, invoice_no, invoice_date, taxable_value, igst, cgst, sgst, itc_availability, raw_json)
      VALUES (${uploadId}, ${r.supplierGstin}, ${r.supplierName}, ${r.invoiceNo}, ${r.invoiceDate}, ${r.taxableValue}, ${r.igst}, ${r.cgst}, ${r.sgst}, ${r.itcAvailability}, ${sql.json(r as never)})`;
  }
  await logActivity({
    actor: input.uploadedBy, actorRole: input.uploadedByRole,
    action: "gstr2b.upload", entity: "gstr2b_upload", entityId: uploadId,
    summary: `Uploaded GSTR-2B for ${input.period} — ${records.length} invoice(s)`,
  });
  return { id: uploadId, count: records.length };
}

export interface Gstr2bUploadRow { id: number; period: string; file_name: string; uploaded_by: string | null; created_at: string; record_count: number }
export async function listGstr2bUploads(): Promise<Gstr2bUploadRow[]> {
  await ensureTables();
  return (await getSql()`
    SELECT u.id, u.period, u.file_name, u.uploaded_by, u.created_at, COUNT(r.id)::int AS record_count
    FROM gstr2b_uploads u LEFT JOIN gstr2b_records r ON r.upload_id = u.id
    GROUP BY u.id ORDER BY u.id DESC LIMIT 50`) as unknown as Gstr2bUploadRow[];
}

export type ReconcileStatus = "matched" | "amount_mismatch" | "missing_in_books" | "missing_in_2b";
export interface ReconcileRow {
  status: ReconcileStatus; supplierGstin: string; supplierName: string; invoiceNo: string; invoiceDate: string;
  gstr2bValue: number | null; bookValue: number | null; vendorBillId: number | null;
}

const AMOUNT_TOLERANCE = 1; // ₹ — vendor_bills.total may not separate tax the same way GSTR-2B does

export async function reconcileGstr2b(uploadId: number): Promise<{ period: string; rows: ReconcileRow[]; summary: Record<ReconcileStatus, number> } | { error: string }> {
  await ensureTables();
  const sql = getSql();
  const [upload] = (await sql`SELECT id, period FROM gstr2b_uploads WHERE id=${uploadId}`) as unknown as Array<{ id: number; period: string }>;
  if (!upload) return { error: "Upload not found." };

  const records = (await sql`SELECT * FROM gstr2b_records WHERE upload_id=${uploadId}`) as unknown as Array<{
    supplier_gstin: string; supplier_name: string; invoice_no: string; invoice_date: string;
    taxable_value: number; igst: number; cgst: number; sgst: number;
  }>;

  const period = upload.period; // "YYYYMM"
  const monthPrefix = `${period.slice(0, 4)}-${period.slice(4, 6)}`;
  const bills = (await sql`
    SELECT b.id, b.bill_no, b.bill_date, b.total, v.gst AS vendor_gstin, v.name AS vendor_name
    FROM vendor_bills b JOIN vendors v ON v.id = b.vendor_id
    WHERE b.bill_date LIKE ${monthPrefix + "%"} OR b.bill_date IS NULL`) as unknown as Array<{
    id: number; bill_no: string; bill_date: string | null; total: number; vendor_gstin: string; vendor_name: string;
  }>;

  const billKey = (gstin: string, no: string) => `${(gstin || "").trim().toUpperCase()}|${(no || "").trim().toLowerCase()}`;
  const billsByKey = new Map(bills.map((b) => [billKey(b.vendor_gstin, b.bill_no), b]));
  const matchedBillIds = new Set<number>();

  const rows: ReconcileRow[] = [];
  for (const r of records) {
    const key = billKey(r.supplier_gstin, r.invoice_no);
    const bill = billsByKey.get(key);
    const gstr2bValue = r.taxable_value + r.igst + r.cgst + r.sgst;
    if (bill) {
      matchedBillIds.add(bill.id);
      const diff = Math.abs(bill.total - gstr2bValue);
      rows.push({
        status: diff <= AMOUNT_TOLERANCE ? "matched" : "amount_mismatch",
        supplierGstin: r.supplier_gstin, supplierName: r.supplier_name, invoiceNo: r.invoice_no, invoiceDate: r.invoice_date,
        gstr2bValue, bookValue: bill.total, vendorBillId: bill.id,
      });
    } else {
      rows.push({
        status: "missing_in_books", supplierGstin: r.supplier_gstin, supplierName: r.supplier_name,
        invoiceNo: r.invoice_no, invoiceDate: r.invoice_date, gstr2bValue, bookValue: null, vendorBillId: null,
      });
    }
  }
  for (const b of bills) {
    if (matchedBillIds.has(b.id)) continue;
    if (!b.vendor_gstin) continue; // no GSTIN on file — nothing to reconcile against
    rows.push({
      status: "missing_in_2b", supplierGstin: b.vendor_gstin, supplierName: b.vendor_name,
      invoiceNo: b.bill_no, invoiceDate: b.bill_date ?? "", gstr2bValue: null, bookValue: b.total, vendorBillId: b.id,
    });
  }

  const summary: Record<ReconcileStatus, number> = { matched: 0, amount_mismatch: 0, missing_in_books: 0, missing_in_2b: 0 };
  for (const r of rows) summary[r.status]++;

  return { period, rows, summary };
}
