import PageHeader from "@/components/PageHeader";
import { getCurrentUser } from "@/lib/erp/session";
import { canWrite } from "@/lib/erp/rbac";
import Gstr2bPanel from "@/components/erp/Gstr2bPanel";

export const dynamic = "force-dynamic";

export default async function Gstr2bPage() {
  const user = await getCurrentUser();
  if (!canWrite(user.role, "gst")) {
    return (
      <>
        <PageHeader title="GSTR-2B Reconcile" subtitle="ITC statement, generated by the government." />
        <section className="panel p-4 text-sm text-[var(--muted)]">Your role ({user.role}) doesn't have access to GST reports.</section>
      </>
    );
  }
  return (
    <>
      <PageHeader
        title="GSTR-2B Reconcile"
        subtitle="GSTR-2B is auto-drafted by the government from your suppliers' filings — download it each month from the GST portal, upload the JSON here, and it's matched against your vendor bills."
      />
      <Gstr2bPanel />
    </>
  );
}
